# Feminicide Narrative History

In 2024 The Met Gala re-imagined Geroges Bizet’s Carmen in a contemporary setting along the U.S.-Mexico border. The crux of the Opera’s ending has the titular character, Carmen, murdered by her lover which is usually expressed as a expression for matters of a jealous heart. This new interpretation did not describe Carmen's tragic murder as a lover’s quarrel but was intended by the production team as a femicide (Cracknell, 2024). The notion that femicide is a modern-day occurrence that happens in a contemporary setting is indicative of the bravado in this scenario. As a case study for understanding fragmented narratives in social media, the anti-femicide movement in Mexico will be used in this research. Just to note, this work does not attempt to theorize reasons why the femicide phenomenon happens, how it happens, or its impact on those affected. What it does do is use its messaging to identify how we as spectators interpret what is being said about the phenomenon.The anti-feminicide movement in Mexico grew from years of feminicide at the border of Mexico and Texas in cd. Juarez Chihuahua and moved across the country (Wright 2001). The first case was documented around 1993 (Pantaleo, 2010).

Aggravated homicide due to gender, specifically females, sexual violence, dehumanization through the image of discarded female remains, or other visual representation of ultraviolence against a woman leading to murder or death is how feminicide came to be known in Mexico (Agnew, 2015). A similar term, feminicide, implies impunity for the state and other judicial structures on top of putting responsibility on the perpetrator (Lagarde 1990, GHRC, 2010). Feminicide is mostly used in Latin-America, but both terms are interchangeable in the literature and official documentation (Toledo Vazquez, 2009). Feminicide will be used in this research.

To be specific, in much of the literature, female homicides and feminicide are described differently where female homicides are random killing regardless of gender, whereas feminicides are the killing for reasons based on gender which have typically been more violent and premeditated, and mostly by someone the victim knew (Lagarde, 2006; Radford, Russel 1992; Firas 2021). Feminicide has been on the rise in recent years, and Mexico is shown to have the second largest rates in Latin America, maintaining a steady rate from one year to the next (Observatorio de Igualdad de Género de América Latina y el Caribe, 2022). This is even despite the 44% of women in ministerial cabinet positions which has increased over the years (Observatorio de Igualdad de Género de América Latina y el Caribe, 2023). Most of the victimized women from different age groups spanning from eleven to sixty years old, and typically represent lower income students, factory workers, and sex workers (Cacho, 2020).

Some reasons for the rise of feminicide in Mexico is linked to a rise in maquiladoras (factories) along the U.S. - Mexico border because of the North American Free Trade Agreement (NAFTA) (Wright 2001; Frias, 2021). Some suggest that the introduction of powerful drug trafficking organizations, and impunity was the main contributor to the phenomena (Campbell 2011; Agnew, 2015). Some more statistical learning studies suggest feminicide is non-existent and compares it to other violent crimes (Albuquerque and Vemala 2014; Hooks 2014). But refuters of this argument suggest that this is “superficial” and does not take into account motives, context, or social connotations of what feminicide is (Agnew, 2015). Others suggest that feminicides are a side-effect of power-hungry militarization strategies of the state (Herrera, Villasenor, Aguilar, 2023). Various reports, news clippings, and datasets have shown not why feminicides happen, but when they happen and to whom in different ways, these topics are explored as framing support in this chapter.

## Traditional Feminicide Narrative Frames

How a feminicide is framed for the Mexican public by the media and political spheres has been a hot topic in gender violence studies. The frames identified in this research were found from patterns in the literature surrounding feminicide frames in Mexico. If a theme emerged in more than one piece of research it was identified and later categorized into an overall frame in an iterative process (Glaser & Strauss, 1967) . This grounded theory approach from the literature is intended to reduce researcher bias in qualitative coding, and identify common frames to inform the methods applied in this research (Charmaz, 2006). This research categorizes the frames as societal, cultural, social movement, and Reframing. Societal frames refer to the representation of a group or community with beliefs and practices, in this case it refers to Mexico society as a whole (Bell 2013; Social Sci LibreTexts, 2024). Societal frames include militarization and organized crime; sex trafficking; social class and the effects of the North American Free Trade Agreement (NAFTA). Cultural frames refer to the beliefs/ideas, traditions, and norms practiced by a society (Bell 2013; Social Sci LibreTexts, 2024). Here, cultural frames regard the behavior of masculinity and femininity, age, and victim blaming. In line with this work’s definition of social movements, this frame is understood as Gardner’s (1999) definition as collective group engagement of non-institutionalized discourse and practice aimed at changing the existing condition of society. Social movement frames refer to the conversations and protests made by individuals, communities, or NGO to address the stigma of feminicide. Humanization discusses the attempt to introduce a new way to view and humanize victims of feminicide and how they affect the overall society. Particularly, most of this research looks at humanizing through an online lens. The frames defined here are not static and can be compared together or within the lens of one another. For example, feminicide is a growing problem in municipalities with large indigenous populations (Firas, 2021; Gress 2023), this could be looked at through the lens of a societal frame that implicates class and economic structure, as noted here, or it can also be understood as a humanizing element that shows feminicide is affecting different types of women the Mexican community. 

### Societal Framing

Much of the early feminicide literature centers around why it happens and looks to Mexico through a societal lens by pointing at the effects of organized crime and international trade. For example, academia has pushed the narrative that feminicide in Mexico began with the implementation of NAFTA because of the mass migration of women to the border looking for work (Wright, 2001;Haley, 2001; Pantalea, 2010). This narrative stems from evidence of an uptick of feminicide reports with the expansion of NAFTA maquiladoras (Livingston, 2004, De Alba and Guzman, 2010). Other research suggests that there is a geopolitical role of the drug war affecting the rise in feminicide in Mexico after drug organizations moved operations from Colombia to Mexico during the war on drugs in the 1990s (Agnew 2015; Corva 2014). Drug-related murders and feminicides as related to the organized crime outlets also known as narcos have been coined narcopolitics by Melissa Wright (2011).  “Narcopolitics” uses the concept of necropolitics (Mbembe, 2008, 2013) to include aspects of feminicide and expand through narco drug traffickers. The terms suggest that the effect of the drug cartel network disrupts the surrounding social structure Wright (2011). In narcopolitics, feminicide and other gender violence is used as a strategy by these narco drug organizations to gain power in the region (Wright, 2011; Agnew 2015). In contrast, the militarization of the state has wider implications not only for feminicide but also for gender violence as impunity and other forms of abuse of power have developed a power struggle between crime organizations (Herrera, Villasenor, Aguilar, 2023). Aspects of militarization have been described as acts of torture and a forced degradation on the ‘enemy’ through means of these gender violence crimes (Wright 2011; Herrera, Villasenor, Aguilar, 2023). In a similar vein, sex trafficking has been suggested as a contributor to feminicide in Mexico (Acharcy, 2005). Calling victims of feminicide potential sex workers connected to a larger illegal organization has been a common approach to signal this is not something that can happen to traditional families (Acharcy, 2005; Revelo Blancos, 2010). These news reports provide information on individual feminicide events which is a common approach, but others have studied the phenomenon in aggregates. 

Some reports show that feminicides have become fairly concentrated where nine of the total 2,446 municipalities account for 13% of national feminicides and 100 others account for 58% of the national total (Sanches, Pesce, 2202). Although not all of these municipalities have a majority of indigenous populations, the concentration around specific municipalities is alarming. Regardless, feminicide is not commonly reported and has been understood as invisible or an issue for future research in academia, where more data can be used (Weil, 2016). The data and ethnographic reports that are available have shown a rise in feminicides in Mexico over the past decade, particularly in indigenous municipalities (Firas, 2021; Gress 2023). There is even support for a growing trend in feminicides even though other violent and bodily integrity crimes have not risen (Sanchez, Pesce 2022; Gress 2023). Through the analysis of regional data covering municipalities, found in data collected from INEGI (National Institute of Statistics and Geography), coupled with the national council of population (CONAPO) from 2001 to 2017 – which is the last year the feminicide microdata was available – Frias (2021) found that there was an annual increase in feminicide overall, with higher rates in indigenous municipalities. The lack of feminicide reporting from indigenous communities could stem from multiple cultural implications of discrimination against indigenous communities (Ravelo Blancos, 2010; Frias 2021; Aldrete, 2023). This study attempts to show a connection between the rise in gender equality and feminicide through a context of conflict coupled with structural discrimination against indigenous peoples. The fact that feminicides along with gender violence are more common in indigenous communities escapes much of academic research which usually focuses on other infamous feminicide locations including cd. Juarez or even Mexico city (Eagan, 2020; Frias 2021).

Regardless, feminicide is not commonly reported and has been understood as invisible or a data issue where there is still work needed (Weil, 2016). In their book, Gender Violence and the US Mexico Border, Dominguez-Ruvalcaba, Corona (2010) suggests that a community that ignores or misrepresents victims of feminicide could be described as a “killing society”, where the perpetrators become more like an empty allegorical figure and victims are sacrificed as an instrument of economic or political interests that push the crime into normalcy. Some visual media even suggests that the Mexican border, and Mexico by proxy, is a country of violence with more empty calls for support (Tabuenca Córdoba, Dominguez-Ruvalcaba, 2010) The notion of pitting the victims’ (forced) livelihoods against their own defense implies an approach to distill the violent crimes within cultural norms. The next framing categories discuss how different cultural behaviors within Mexican society are used to frame a feminicide in the media.

### Cultural Frames

When initial feminicide reports were being made, particularly in cd. Juarez, people tried to make sense of the phenomenon and began looking into the victim for lack of a perpetrator. Efforts in attempting to record cases have been done by the UN and Mexican government entities, like Secretariado Ejecutivo del Sistema Nacional de Seguridad Pública, but still miss many cases that are not reported or misreported (Sim, 2018; Lopez, 2019; UN Women, 2022). In fact, a study using 2,527 articles about feminicide in Mexico from three news sources (July 2014 - December 2017) found that victims were represented negatively, more so than their actual perpetrators (Aldrete, 2023). This attempt to understand how victims are perceived in news media revealed negative narratives against victims related to social contexts and unique or specialized cases (Aldrete, 2023). Information resources available to journalists reporting on feminicide were found to be coming from mostly male sources, which could provide some type of bias (Tiscareno, Villanueva, Santorum, 2023). Tiscareno, Villanueva, Santorum (2023) analyzed texts from 2000-2015 from 4 media publications and suggest that official sources come through male informants, whereas sources with less official titles on the matter come from females –  which overall reduces the importance of the subject. Essentially, those in higher government positions who comment on the nature of the crime are male, whereas friends and family members tend to be female. Other studies show how journalistic articles provide incomplete information with an inability to balance the “factual” and the “contextual” (Corona, 2010). A review of several print newspapers shows that the typical journalistic piece loses concrete information such as why a feminicide happens or a look into who the perpetrator is, and in place attempts to contextualize the situation for a reader’s attention (Corona, 2010).

Attempts to make sense of the crimes or mitigate outrage, the tactic of “victim blaming” is expressed throughout the media in various forms. The idea of the “public woman” was set by the Mexican media as a narrative to show that the victim was at fault for staying out too late, talking to too many men, or just walking in the wrong place at the wrong time (Wright, 1999). Here, putting the victim at fault implements the victim-blaming aspect of the cultural frame. It plays with the idea of guilt by using preconceived beliefs about who a woman is and how they contribute to traditional society as a foundation for blaming women who stray from the stereotype (Tiscareño García, E., Vázquez Parra, J. C., & Arredondo Trapero, F. G.,  2021). Framing feminicides through victim-blaming is based on Mexico’s dominant patriarchal ideology (Tiscareño García, E., Vázquez Parra, J. C., & Arredondo Trapero, F. G., 2021). What these researchers suggest is that the victims were different agents of society with varying levels of morals and habits that could have lead them to their death– the fact that a perpetrator was to blame or even existant, is out of the question for these “public women'' (Flores, 2017; Tiscareño García, E., Vázquez Parra, J. C., & Arredondo Trapero, F. G. (2021). Initially, it was easier to push this narrative because many of the victims moved to the border from southern Mexican states, in search of work (Ravelo, 2017). These women were given the name “public women '' as they became more financially and socially independent. More women were seen out at bars, clubs, and shopping which took on negative connotations for feminicide victims in the media as someone situated along the fringe of society (Dominguez-Ruvalcaba, Corona.2010; Rojas, 2014). Similarly, the reproduction of the cultural dichotomy of girlhood and womanhood shows up as the victims in the media through young and sweet or older and promiscuous (Pareda 2012; Butcher, 2015; Agnew, 2015)

The framing of female independence as “public woman” is in contrast with machismo norms embedded in the culture. Machismo refers to a (usually) negative form of masculinity that describes male dominance and superiority (Blimes, 1992). Although macho can also be used as a positive way to signify masculinity and identity, the negative connotation still stands (Blimes, 1992; Segrest, Romero, Domke-Damonte 2003). Much of the literature suggests that a high level of machismo-ism in Mexico led to violence because women were becoming more independent and gender norms were shifting (Wright 1999; Blimes, 1992; Segrest, Romero, Domke-Damonte 2003, de la Morena, Ines 2020). The morays of traditional masculine and feminine cultural practices are found to be practiced in schools and other institutions where children and adolescents are exposed to the dichotomy and suggested as a contribution to the unequal climate of overall gender violence (Alfonso, 2012). Because these norms have been around for a long time, some suggest that there is an avoidance to implement change in gender discrimination practices in schools, the workplace and other public locations (Segrest, Romero, Domke-Damonte 2003; (Alfonso, 2012).

### Social Movement Frames

Since the initial recorded cases in 1993 there have been many movements led independently by mothers, friends and extended family. Most of them are small and focus on separate cases (Fregoso, Bejerano, 2010). Some policies have also been put into place to prosecute aggressors and attempt to record data, and there have been bigger movements as time has passed (Massa Roldan, 2021; True, 2021). Specifically along the border in cd Juarez where the first influx of reports began, the social movement organizations (SMOs) protesting feminicide have their own way of framing their grievances. Starr (2017) found frame patterns from five different organizations that broadcast frames through their mission statements. The frames of these movements were described as master frames – the general idea of the movement, diagnostic frames – the grievances of the movement; and motivational frames – the call to action (Snow & Benford, 1988, 1992, 2000; Starr 2017). Overall, the master frames that were found from the anti-feminicide SMOs at the border were Injustice; Western Feminist: Anti-patriarchy, anti-violence, anti-war; Violence Against Women; and Human Rights (Starr, 2017). The diagnostic frames found overall were impunity; patriarchy; and culture of violence against women (Starr, 2017). These groups are motivated by their organizational services provided, grassroots meetings and actions towards policy and labor changes (Starr, 2017). The mix of framing devices for these social movements follows along with frames found in the literature of this research. Unless the SMO is a service providing NGO and pushes injustice or impunity, efforts of grassroots organizations seem to be identified with by the community, but not motivational enough to bring out a larger collective action (Starr, 2017). Here, the social movement frames with more cultural relevance have greater chances of motivating the population. The frame analysis performed by Starr (2017) also reveals important movement dynamics that can lead future movements to examine the interactions between outsiders, local elites, and grassroots constituencies.

Feminicide is conceptualized with respect to human rights violations through broader terms including the right to access justice, prohibition of torture and other violent and inhumane crimes (Hefti, 2022). By comparing feminicide to various violations, it is framed to be added as a human rights violation and compared to other international core crimes (Hefti, 2022; Ramirez, 2021). In an attempt to implement these laws, 2008 saw a change in the Mexican legal structure that allowed private prosecution, or third parties, into the courts as litigation law. This opportunity enabled activists to litigate feminicide cases and attempt to have international human rights law seen at the state level, others pushed to integrate domestic violence courts as a solution (Michel, 2020; Ramirez, 2021). A case prosecuting a defendant accused of an attempted murder of a woman was the first case where an NGO (Non-Governmental Organization) participated (Michel, 2020). With a review of governmental data from two Mexican states, the author argues that the changes have enabled a strategic litigation through NGOs to improve compliance with international human rights law, and has been able to use these laws to press for more accountability of the state (Michel, 2020).

##### Individuals

Mothers and other family members who have been personally affected by feminicide have been participating in social movements and other community outreach programs as a way of coping with their experience. For example, interviews with these types of individuals revealed how they frame aspects of their situation as soundbites, guilt, and resilience (Ravelo Blancos, 2010).  Ravelo Blanco (2010) concluded that most families in Mexico think they’re immune to the horrific act of violence because of how it’s reported, particularly that the family should feel guilty or that their experience is just another soundbite for a political campaign. But when feminicide happens to a loved one the need to become more active in the community is a necessary practice in therapy and a tangible way to feel like they are taking action (Ravelo Blancos, 2010). This is also a way for these families to reframe their experiences into something hopeful for the future.

##### Protest

As this problem persists, people took to the streets on international women’s day, March 8th 2020 after a 10% rise in 2019 (Sheridan, 2020). One intention of this large protest was to give rise to more conversation about the violence and show outrage for what is happening in the country compared to traditional ways of dealing with the problem as thinking it only happens to someone else (Seridan, 2020). Before the 2020 protest, there were other bursts of public protest across Mexico that targeted individual events, not just anti-feminicide overall. For example, after a failure to apprehend officials, women met at the prosecutor’s office in Mexico city to protest and even “doused” a security officer in pink glitter (Rivera Garza, 2020). At the end of 2020, a group of women, El Bloque Negro Black Blcok, took over the federal Human Rights Commision building in Mexico City to house victims of feminicide and gender violence who had been trying to get government support (Green, Razo, 2020). These events were not unique for this time, but they were special because they gained a lot of attention online which was then picked up by other media outlets. The women who took over the building, and threw pink glitter at security officials were called feminists and activists in the media (Green, Razo, 2020; Ferri, 2020; Demos, Servin 2020). Usually in Mexico these terms implement a negative connotation that brought about sighs and rolled eyes from the public (Rivera Garza, 2020). Regardless of this reaction, awareness for the anti-feminicide movement coupled with the anti-gender violence movement was getting through to the public via online content and people were not considering victims as “public women” or strangers, but trying to bring attention to the situation.

### Reframing

There have been attempts to reframe feminicide crimes in the media that speak to existing frames by humanizing victims and remembering them in a positive light. Some expand on the community at large, some use social media to speak freely, while others attempt to view feminicides on a geographical scale. Overall, this research denotes humanizing as a way to implement a different approach to consuming news about feminicides in Mexico.

##### Collective Memory

Multiple social media campaigns beginning with artists and creatives spread across the internet to bring awareness to gender violence. Earliest of these was in 2015 when a group of artists came up with the hashtag #RopaSucia (roughly translates to ‘dirty laundry’) was used to first showcase incidents of misogyny in their own academic institutions and creative communities, and encouraged others to do the same from their own communities (Rivera Garza, 2020). From then, others started their own campaigns including topics like “MiPrimerAcoso ‘ my first harassment’ - relating to someone’s first sexual harassment, #MareaVerde ‘the green wave’ - relating to abortion rights, and #niunamas ‘not one more’ - relating to feminicide.These campaigns have brought awareness and support for these causes and a reframing of the idea that these types of events are more widespread than they had thought. It expresses the community struggle that comes from crimes of feminicide and gender violence. Alternatively, these online campaigns also brought about a frame of pushback which claimed calls of inaccurate or distorted stories were made by the accusers (Rivera Garza, 2020; Aldrete 2023).

Aside from online support of community action, there is a parallel phenomenon happening in the real world through the frame of collective memory and collective justice. A review of various newspaper photos of mothers remembering their murdered or missing daughters through fragmented visual aesthetic provides an interpretation of pain that is articulated by those who outlive the victims of feminicide (Vargas, 2019). A fragmented visual aesthetic refers to fragmented memory of incomplete events, and what we remember from them through objects, images and memories (Ricoeur, 2013; Benjamin 2006). Much of the photographs analyzed show mothers holding portraits of their missing or assassinated daughters with flowers or personal items (Vargas, 2019). The ensemble of images, including the ensemble of gatherings for when these images were posted is a new way to spread the narrative of feminicide through a collective visual memory of loved ones.

##### Data Production

With more attempts to keep the memory of loved ones alive, documenting who victims were before they were murdered has become a new humanizing device. Independent data collection happens because authorities fail to report, examine, or investigate the crimes properly, if at all. Evidence is not stored correctly or lost, forensic tests and processes are mishandled and ignored which results in inadequate or missing data. (Amnesty International 2021, Suarez Val). This is also due to a lack of resources, specializations, and conditions for state investigators to carry out these duties properly (Amnesty International 2021; Massa Roldan, et al. 2021). Because of these shortcomings, families and other citizens take it upon themselves to investigate or put pressure on authorities through their own means, or international support (Wilson, Mcllwaine, Boesten Jelke 2021; Amnesty International 2021).

In addition to fear of victim blaming, impunity, lack of resources, interpretation of the crime, and corruption are some reasons for low documentation (Massa Roldan, et al. 2021; Datacivica, 2023), some people have become vigilantes or citizen scientists who collect and record data. For example maps are a very common way to document Feminicides in Latin America. In 2016, Maria Salguero published a map of all of the recorded Feminicides by the government and media or news sources that have happened in Mexico since 2011 (Salguero, 2016). Salguero tries to include as many details of each case on the map, details of how the victim was murdered, who they might have been or who they were associated to, the offenders, motivations, homicide patterns and crime scenarios. The intention is to provide an identity for these women who have been murdered and are seen as a statistic, if they are seen at all (Isaad, 2019). The idea of providing an identity for the victim is a narrative many leaders of the anti-Feminicide movement want to push forward in the national conversation. For example, Ellas Tienen Nombre “They have a name”, is an online site that maintains a digital map of Feminicides in Ciudad Juarez, Chihuahua tracked by an independent researcher who shows pictures of the victims, details of who they are and any other information found online and in police reports (Ramirez, 2023). Much of this information is found by creating keyword notifications on social media like Facebook, Twitter and Instagram and pulling from the images, videos, and user comments that accompany these events (ESOCITE/4S, 2022). This idea of providing an identity for the victims including image, music and bio is one way individuals in the movement are pushing for change (ESOCITE/4S, 2022; UN Women, 2022).

### Ellas Tienen Nombre and Your contribution - compare to collected social media data?

Efforts of these citizen data scientists approach feminicide reporting with a focus on data and data counting. The term data counting was coined by Catherine D’Ignazio after working with research labs that observe citizen data production (D’Ignazio, 2023). These labs include Data + Feminism; Data Against Feminicide; and Iniciativa Latinoamericana por los Datos Abiertos (ILDA - Latin American Initiative for Open Data). Data counting refers to the production of data in relation to feminicide and gender-killing by data activists in Latin America (D’Ignazio, 2023). It stems from D’Ignazio’s book Data Feminism and has been further described as missing or counter data to mainstream counting institutions (Fumega, 2021; D’Ignazio, 2023). For example, common outlets get their data from government organizations that lack contextual information, and add or remove variables with each new version of data (Suarez Val, 2021; Sanchez, Pesce, 2022). In an ontological comparison of citizen data scientist data and institutional based data from Uruguay, the citizen dataset identifies a date, location and a substantial relation to the perpetrator when known whereas the institutional dataset sets up the information on the age and how the victim died, and shows the age and what (if any) weapon the perpetrator used, with less emphasis on the location (Suarez Val, 2021). Although these datasets describe the situation in Uruguay, it provides insight on small differences between citizen and institutional data that lend for different institutional pretenses, motivations, resources, and importance of those involved. Another attempt to support data production efforts by cutting down large labor time and emotional effort is a work in progress that attempts to automate detection of feminicide events online using information retrieval methods across Google (D’Ignazio, Suarez Val, Fumega et al, 2020). The model is said to have a high accuracy 81% of identifying feminicide events from an annotated dataset, from these outcomes, an automated identifier is in the works (D’Ignazio, Suarez Val, Fumega et al, 2020).

Differences and inconsistencies in the data and in data collection have led some to push for data standardization when it comes to producing and collecting feminicide data. As feminicide cases in Mexico are mismanaged and continue to rise (Sanchez, Pesce 2022), standardization of feminicide data production has the potential to inform evidence-based decision and policy making. Initial efforts build on work done by the ECLAC Gender Equality Observatory and the United Nations High Commissioner for Human Rights, which has a standardization via the Latin American Model Protocol for the Investigation of Gender-Related Killings of Women (the Bogotá Protocol) (Fumega, 2019). An exploratory study began in 2017 by the ILDA to understand different approaches to data production and uses, and how these approaches help identify why there are problems with how feminicide is reported (Fumega, 2019). ILDA attempted to identify and fill these gaps found through an action-research methodology that considers seven approaches for standardization, these approaches include: 1) acknowledging different interpretations and contexts, 2) implement different levels of access; 3) work with manual compilations of pre-established systems; 4) integrate gender perspectives; 5) allow for revisions with new evidence; 6) draw regional comparisons; 7) stay open to the use of data analysis and machine learning (Fumega, 2019). These approaches and considerations were established as recommendations and workshops in Argentina and Uruguay; in this case Mexico has the potential to be included as it is also a Latin American country.
