# Social Media and Fragmentation

Image fragments have been compared to memory fragments and described as self-contained dispersed and potentially leading nowhere (Strassler, 2022). These image fragments representing a point in time can be understood as both the past and present stemming from Walter Benjamin’s notion of the dialectical image described by Strassler (2022). Benjamin”s dialectical image brings about an idea of assembling fragmented images to construct a new form of critical memory (Strassler, 2022) has the potential to present the collection of images in a narrative structure. The presentation of a narrative in new digital media such as online games, social media, blogs, and online forums can provide a non-traditional narrative structure that presents information from various perspectives. According to Skains et al (2015), new digital media introduces multimodality, poly-linearity and user/creator interaction. These various affordances provided by new digital media affect user experience and lead to multiple aspects of a topic from various contributors that causes fragmentation. Fragmentation has been shown to provide a lack of control for the narrative but presents a reconstruction of the narrative that affects the human experience that builds a collaboration between the content, device and viewer (Skains, 2015).

Some research explores the idea that the mediatization of social media has increased fragmentation of information among social media sites because of the affordances provided by these platforms (Sadler, 2021). Since then, arguments against the fragmentation of content on social media indicate an overwhelming amount of “supersaturation” (Gilpin, 2001) or arguments of a deluge of information and not an easy way to connect them (Manovich, 2001). There have been attempts to organize this fragmentation by third party tools or even intelligent uses of keywords and hashtags to find consistency in a topic (Sadler, 2021). Even algorithms are structured to present relevant content to users based on their activity and find some kind of semblance between what a user sees most. Previous research on image fragmentation in social media looks at the activity metrics and sentiment correlations of images with domain-based frameworks in both quantitative and qualitative methods (Gilpin, 2010; Chen et al, 2020; van den Broek, 2021). They find that visual fragmentation across channels or users can provide divergent or siloed narratives, particularly while reviewing higher ranked posts (Chen et al, 2020) or content spread throughout local and broader communities (Wah, 2021; Albrecht et al 2022). Some work on fragmentation and circulation reviews implications of political participation from visual social media content and finds that particular image features and narrative frames impact political participation (Chapman, 2016; Krause, 2018; Geise, 2021).

—------------------------------------------------------------------------------------------

### Social Movement Narrative Framing and Fragmentation

The affordances of social media enable interaction with the news and boost coordination, and transactions instead of screen consumption (Geha, 2018). As images, videos, and memes about a social cause have become more common for circulating information, these newer types of engagement can be understood as activity within the social movement (Earl 2003, Turner, 2013). Roberta Garner (1999) defines social movements as “collectivities engaged in noninstitutionalized discourses and practices aimed at changing the existing condition of society”. The engagement of this collective, or group, can include digital and face to face protest, communication campaigns, petitions and the like (Earl, 2011). Connective action on social media can sustain long-term participation for a movement after a mobilizing event, and enabled movements like the Women's March to become a broader event (Syed, Silva, 2023). Although, understanding how some grassroots involvement in social movements using social media is limited because of a lack of knowledge of grassroots use on social media and potential cases for proactive use of social media for long-term empowerment (Leong, et. al, 2018). By keeping up with social media updates and information circulation, social movements might be able to build better mobilization power online (Xiao, Mina, 2019). More specifically, images and visual messaging of social movements have become popular content on social media in the past decade (Earl, Garrett, 2016; Moore-Gilbert et al, 2017) and each event representing a social movement appears to be independent of the one before (Tufecki, 2017). When users consume information on social media about a social movement event, they get fragments of the whole narrative. Information regarding an event happening within a community or specific location will have different narrative frames locally and for a wider audience (Moore-Gilbert et al, 2017; Wah, 2021). Because social movements depend on society's collective action (Bennet, Segerberg, 2012) and much of online collective action is influenced by online messaging, structural changes in the community’s information circulation can change over time (Freelon et al, 2016), especially when bits of information reinforce only part of a narrative. This fragmentation can distort user perception, misinform the public, and impact collective action. With this problem in mind, the objective of this dissertation research will be to explore how narratives can provide context to fragmentation from social media image content representing a social movement.
